<?php

namespace App\Support\Bpjs;

class BpjsTesterCatalog
{
    public function groups(): array
    {
        return [
            [
                'id' => 'vclaim',
                'label' => 'VClaim',
                'items' => [
                    $this->query(
                        id: 'peserta',
                        title: 'Cari Peserta',
                        method: 'GET',
                        path: '/api/v1/bpjs/peserta',
                        description: 'Pencarian peserta berdasarkan nomor kartu atau NIK.',
                        fields: [
                            ['key' => 'nomor', 'label' => 'Nomor Peserta', 'type' => 'text', 'value' => '0001234567890'],
                            ['key' => 'tipe', 'label' => 'Tipe', 'type' => 'select', 'value' => '1', 'options' => [
                                ['label' => '1 - Nomor Kartu', 'value' => '1'],
                                ['label' => '2 - NIK', 'value' => '2'],
                            ]],
                        ],
                        mockResponse: [
                            'metaData' => [
                                'code' => '200',
                                'message' => 'OK',
                            ],
                            'response' => [
                                'peserta' => [
                                    'cob' => [
                                        'nmAsuransi' => null,
                                        'noAsuransi' => null,
                                        'tglTAT' => null,
                                        'tglTMT' => null,
                                    ],
                                    'hakKelas' => [
                                        'keterangan' => 'KELAS I',
                                        'kode' => '1',
                                    ],
                                    'informasi' => [
                                        'dinsos' => null,
                                        'noSKTM' => null,
                                        'prolanisPRB' => null,
                                    ],
                                    'jenisPeserta' => [
                                        'keterangan' => 'PEGAWAI SWASTA',
                                        'kode' => '13',
                                    ],
                                    'mr' => [
                                        'noMR' => null,
                                        'noTelepon' => null,
                                    ],
                                    'nama' => 'TRI M',
                                    'nik' => '3319022010810007',
                                    'noKartu' => '0011336526592',
                                    'pisa' => '1',
                                    'provUmum' => [
                                        'kdProvider' => '0138U020',
                                        'nmProvider' => 'KPRJ PALA MEDIKA',
                                    ],
                                    'sex' => 'L',
                                    'statusPeserta' => [
                                        'keterangan' => 'AKTIF',
                                        'kode' => '0',
                                    ],
                                    'tglCetakKartu' => '2016-02-12',
                                    'tglLahir' => '1981-10-10',
                                    'tglTAT' => '2014-12-31',
                                    'tglTMT' => '2008-10-01',
                                    'umur' => [
                                        'umurSaatPelayanan' => '35 tahun ,1 bulan ,11 hari',
                                        'umurSekarang' => '35 tahun ,2 bulan ,10 hari',
                                    ],
                                ],
                            ],
                        ],
                    ),
                    $this->query(
                        id: 'sep-search',
                        title: 'Cari SEP',
                        method: 'GET',
                        path: '/api/v1/bpjs/sep',
                        description: 'Pencarian detail SEP berdasarkan nomor SEP.',
                        fields: [
                            ['key' => 'no_sep', 'label' => 'Nomor SEP', 'type' => 'text', 'value' => '0301R0110326V000001'],
                        ],
                        mockResponse: [
                            'metaData' => ['code' => '200', 'message' => 'Sukses'],
                            'response' => [
                                'assestmenPel' => [
                                    'kode' => '1',
                                    'nama' => 'Poli spesialis tidak tersedia pada hari sebelumnya',
                                ],
                                'catatan' => 'testinsert RJ',
                                'cob' => '0',
                                'diagnosa' => 'Insulin-dependent diabetes mellitus',
                                'dpjp' => [
                                    'kdDPJP' => '31348',
                                    'nmDPJP' => 'CIiNatXXAXSkrIrPId,ManFs.SDDMe',
                                ],
                                'eSEP' => 'False',
                                'flagProcedure' => [
                                    'kode' => '0',
                                    'nama' => 'Prosedur tidak berkelanjutan',
                                ],
                                'informasi' => null,
                                'jnsPelayanan' => 'Rawat Jalan',
                                'katarak' => '0',
                                'kdPenunjang' => [
                                    'kode' => '0',
                                    'nama' => '',
                                ],
                                'kdStatusKecelakaan' => '0',
                                'kelasRawat' => 'Kelas 3',
                                'klsRawat' => [
                                    'klsRawatHak' => '3',
                                    'klsRawatNaik' => null,
                                    'pembiayaan' => null,
                                    'penanggungJawab' => null,
                                ],
                                'kontrol' => [
                                    'kdDokter' => null,
                                    'nmDokter' => null,
                                    'noSurat' => null,
                                ],
                                'lokasiKejadian' => [
                                    'kdKab' => null,
                                    'kdKec' => null,
                                    'kdProp' => null,
                                    'ketKejadian' => null,
                                    'lokasi' => null,
                                    'tglKejadian' => null,
                                ],
                                'nmstatusKecelakaan' => 'Bukan Kecelakaan',
                                'noRujukan' => null,
                                'noSep' => '0301R0111125V000011',
                                'penjamin' => null,
                                'peserta' => [
                                    'asuransi' => null,
                                    'hakKelas' => 'Kelas 3',
                                    'jnsPeserta' => 'MANDIRI',
                                    'kdStatusPRB' => null,
                                    'kelamin' => 'P',
                                    'nama' => 'ARMSTIOFIALR',
                                    'noKartu' => '0002482505324',
                                    'noMr' => 'MR0652',
                                    'potensiPRB' => null,
                                    'statusPRB' => null,
                                    'tglLahir' => '1983-09-07',
                                ],
                                'poli' => 'INSTALASI GAWAT DARURAT',
                                'poliEksekutif' => '0',
                                'tglSep' => '2025-11-25',
                                'tujuanKunj' => [
                                    'kode' => '0',
                                    'nama' => 'Normal',
                                ],
                            ],
                        ],
                    ),
                    $this->query(
                        id: 'sep-riwayat',
                        title: 'Riwayat Pelayanan Peserta',
                        method: 'GET',
                        path: '/api/v1/bpjs/sep-riwayat',
                        description: 'Riwayat pelayanan peserta berdasarkan nomor kartu BPJS.',
                        fields: [
                            ['key' => 'no_kartu', 'label' => 'Nomor Kartu', 'type' => 'text', 'value' => '0001234567890'],
                        ],
                        mockResponse: [
                            'metaData' => ['code' => '200', 'message' => 'Sukses'],
                            'response' => [
                                'histori' => [
                                    [
                                        'diagnosa' => 'A00.1 - Cholera due to Vibrio cholerae 01, biovar eltor',
                                        'jnsPelayanan' => '1',
                                        'kelasRawat' => 'Kelas 1',
                                        'namaPeserta' => 'STAMI',
                                        'noKartu' => '0001160271256',
                                        'noSep' => '0301R0110818V200084',
                                        'noRujukan' => '0301U01108180200084',
                                        'poli' => '',
                                        'ppkPelayanan' => 'RS YOS SUDARSO',
                                        'tglPlgSep' => '2018-07-11',
                                        'tglSep' => '2018-07-09',
                                    ],
                                    [
                                        'diagnosa' => 'A00.1 - Cholera due to Vibrio cholerae 01, biovar eltor',
                                        'jnsPelayanan' => '2',
                                        'kelasRawat' => null,
                                        'namaPeserta' => 'STAMI',
                                        'noKartu' => '0001160271256',
                                        'noSep' => '0301R0110818V100085',
                                        'noRujukan' => '0301U01108180201084',
                                        'poli' => '',
                                        'ppkPelayanan' => 'RS YOS SUDARSO',
                                        'tglPlgSep' => '2018-08-09',
                                        'tglSep' => '2018-08-09',
                                    ],
                                ],
                            ],
                        ],
                    ),
                    $this->form(
                        id: 'sep-insert',
                        title: 'Insert SEP',
                        method: 'POST',
                        path: '/api/v1/bpjs/sep',
                        description: 'Membuat SEP baru ke BPJS VClaim.',
                        fields: [
                            ['path' => 'request.t_sep.noKartu', 'label' => 'No. Kartu', 'type' => 'text', 'value' => '0001234567890'],
                            ['path' => 'request.t_sep.tglSep', 'label' => 'Tanggal SEP', 'type' => 'date', 'value' => '2026-03-19'],
                            ['path' => 'request.t_sep.ppkPelayanan', 'label' => 'PPK Pelayanan', 'type' => 'text', 'value' => '0301R011'],
                            ['path' => 'request.t_sep.jnsPelayanan', 'label' => 'Jenis Pelayanan', 'type' => 'select', 'value' => '2', 'options' => [
                                ['label' => '1 - Rawat Inap', 'value' => '1'],
                                ['label' => '2 - Rawat Jalan', 'value' => '2'],
                            ]],
                            ['path' => 'request.t_sep.klsRawat.klsRawatHak', 'label' => 'Hak Kelas', 'type' => 'select', 'value' => '3', 'options' => [
                                ['label' => 'Kelas 1', 'value' => '1'],
                                ['label' => 'Kelas 2', 'value' => '2'],
                                ['label' => 'Kelas 3', 'value' => '3'],
                            ]],
                            ['path' => 'request.t_sep.noMR', 'label' => 'No. MR', 'type' => 'text', 'value' => 'RM-001'],
                            ['path' => 'request.t_sep.rujukan.asalRujukan', 'label' => 'Asal Rujukan', 'type' => 'select', 'value' => '1', 'options' => [
                                ['label' => '1 - Faskes 1', 'value' => '1'],
                                ['label' => '2 - Faskes 2', 'value' => '2'],
                            ]],
                            ['path' => 'request.t_sep.rujukan.tglRujukan', 'label' => 'Tanggal Rujukan', 'type' => 'date', 'value' => '2026-03-18'],
                            ['path' => 'request.t_sep.rujukan.noRujukan', 'label' => 'No. Rujukan', 'type' => 'text', 'value' => 'RJK-001'],
                            ['path' => 'request.t_sep.rujukan.ppkRujukan', 'label' => 'PPK Rujukan', 'type' => 'text', 'value' => '0301P001'],
                            ['path' => 'request.t_sep.catatan', 'label' => 'Catatan', 'type' => 'textarea', 'value' => 'Kontrol dari dashboard admin'],
                            ['path' => 'request.t_sep.diagAwal', 'label' => 'Diagnosa Awal', 'type' => 'text', 'value' => 'K30'],
                            ['path' => 'request.t_sep.poli.tujuan', 'label' => 'Poli Tujuan', 'type' => 'text', 'value' => 'INT'],
                            ['path' => 'request.t_sep.poli.eksekutif', 'label' => 'Poli Eksekutif', 'type' => 'select', 'value' => '0', 'options' => [
                                ['label' => '0 - Tidak', 'value' => '0'],
                                ['label' => '1 - Ya', 'value' => '1'],
                            ]],
                            ['path' => 'request.t_sep.cob.cob', 'label' => 'COB', 'type' => 'select', 'value' => '0', 'options' => [
                                ['label' => '0 - Tidak', 'value' => '0'],
                                ['label' => '1 - Ya', 'value' => '1'],
                            ]],
                            ['path' => 'request.t_sep.katarak.katarak', 'label' => 'Katarak', 'type' => 'select', 'value' => '0', 'options' => [
                                ['label' => '0 - Tidak', 'value' => '0'],
                                ['label' => '1 - Ya', 'value' => '1'],
                            ]],
                            ['path' => 'request.t_sep.jaminan.lakaLantas', 'label' => 'Laka Lantas', 'type' => 'select', 'value' => '0', 'options' => [
                                ['label' => '0 - Tidak', 'value' => '0'],
                                ['label' => '1 - Ya', 'value' => '1'],
                            ]],
                            ['path' => 'request.t_sep.tujuanKunj', 'label' => 'Tujuan Kunjungan', 'type' => 'select', 'value' => '0', 'options' => [
                                ['label' => '0 - Normal', 'value' => '0'],
                                ['label' => '1 - Prosedur', 'value' => '1'],
                                ['label' => '2 - Konsul Dokter', 'value' => '2'],
                            ]],
                            ['path' => 'request.t_sep.flagProcedure', 'label' => 'Flag Procedure', 'type' => 'text', 'value' => ''],
                            ['path' => 'request.t_sep.kdPenunjang', 'label' => 'Kode Penunjang', 'type' => 'text', 'value' => ''],
                            ['path' => 'request.t_sep.assesmentPel', 'label' => 'Assessment Pelayanan', 'type' => 'text', 'value' => ''],
                            ['path' => 'request.t_sep.skdp.noSurat', 'label' => 'No. Surat SKDP', 'type' => 'text', 'value' => ''],
                            ['path' => 'request.t_sep.skdp.kodeDPJP', 'label' => 'Kode DPJP SKDP', 'type' => 'text', 'value' => ''],
                            ['path' => 'request.t_sep.dpjpLayan', 'label' => 'DPJP Layan', 'type' => 'text', 'value' => '12345'],
                            ['path' => 'request.t_sep.noTelp', 'label' => 'No. Telepon', 'type' => 'text', 'value' => '081234567890'],
                            ['path' => 'request.t_sep.user', 'label' => 'User', 'type' => 'text', 'value' => 'admin-ui'],
                        ],
                        mockResponse: [
                            'metaData' => ['code' => '200', 'message' => 'Sukses'],
                            'response' => [
                                'sep' => [
                                    'assestmenPel' => '1',
                                    'catatan' => 'testinsert RJ',
                                    'diagnosa' => 'A15 - Respiratory tuberculosis, bacteriologically and histologically confirmed',
                                    'flagProcedure' => '',
                                    'informasi' => [
                                        'dinsos' => null,
                                        'eSEP' => 'True',
                                        'noSKTM' => null,
                                        'prolanisPRB' => null,
                                    ],
                                    'jnsPelayanan' => 'R.Jalan',
                                    'kdPenunjang' => '',
                                    'kdPoli' => 'INT',
                                    'kelasRawat' => '-',
                                    'noRujukan' => '0050B1070223P000004',
                                    'noSep' => '0301R0010323V000039',
                                    'penjamin' => '-',
                                    'peserta' => [
                                        'asuransi' => '-',
                                        'hakKelas' => 'Kelas 3',
                                        'jnsPeserta' => 'PBI (APBN)',
                                        'kelamin' => 'Perempuan',
                                        'nama' => 'ARSTNUU',
                                        'noKartu' => '0002802875185',
                                        'noMr' => 'MR5185',
                                        'tglLahir' => '1944-02-24',
                                    ],
                                    'poli' => 'PENYAKIT DALAM',
                                    'poliEksekutif' => 'Tidak',
                                    'tglSep' => '2023-03-30',
                                    'tujuanKunj' => '2',
                                ],
                            ],
                        ],
                    ),
                    $this->form(
                        id: 'sep-update',
                        title: 'Update SEP',
                        method: 'PUT',
                        path: '/api/v1/bpjs/sep',
                        description: 'Mengubah SEP yang sudah ada.',
                        fields: [
                            ['path' => 'request.t_sep.noSep', 'label' => 'No. SEP', 'type' => 'text', 'value' => '0301R0110521V000037'],
                            ['path' => 'request.t_sep.klsRawat.klsRawatHak', 'label' => 'Hak Kelas', 'type' => 'select', 'value' => '3', 'options' => [
                                ['label' => 'Kelas 1', 'value' => '1'],
                                ['label' => 'Kelas 2', 'value' => '2'],
                                ['label' => 'Kelas 3', 'value' => '3'],
                            ]],
                            ['path' => 'request.t_sep.klsRawat.klsRawatNaik', 'label' => 'Kelas Naik', 'type' => 'text', 'value' => ''],
                            ['path' => 'request.t_sep.klsRawat.pembiayaan', 'label' => 'Pembiayaan', 'type' => 'text', 'value' => ''],
                            ['path' => 'request.t_sep.klsRawat.penanggungJawab', 'label' => 'Penanggung Jawab', 'type' => 'text', 'value' => ''],
                            ['path' => 'request.t_sep.noMR', 'label' => 'No. MR', 'type' => 'text', 'value' => '00469120'],
                            ['path' => 'request.t_sep.catatan', 'label' => 'Catatan', 'type' => 'textarea', 'value' => ''],
                            ['path' => 'request.t_sep.diagAwal', 'label' => 'Diagnosa Awal', 'type' => 'text', 'value' => 'E10'],
                            ['path' => 'request.t_sep.poli.tujuan', 'label' => 'Poli Tujuan', 'type' => 'text', 'value' => 'IGD'],
                            ['path' => 'request.t_sep.poli.eksekutif', 'label' => 'Poli Eksekutif', 'type' => 'select', 'value' => '0', 'options' => [
                                ['label' => '0 - Tidak', 'value' => '0'],
                                ['label' => '1 - Ya', 'value' => '1'],
                            ]],
                            ['path' => 'request.t_sep.cob.cob', 'label' => 'COB', 'type' => 'select', 'value' => '0', 'options' => [
                                ['label' => '0 - Tidak', 'value' => '0'],
                                ['label' => '1 - Ya', 'value' => '1'],
                            ]],
                            ['path' => 'request.t_sep.katarak.katarak', 'label' => 'Katarak', 'type' => 'select', 'value' => '0', 'options' => [
                                ['label' => '0 - Tidak', 'value' => '0'],
                                ['label' => '1 - Ya', 'value' => '1'],
                            ]],
                            ['path' => 'request.t_sep.jaminan.lakaLantas', 'label' => 'Laka Lantas', 'type' => 'select', 'value' => '0', 'options' => [
                                ['label' => '0 - Tidak', 'value' => '0'],
                                ['label' => '1 - Ya', 'value' => '1'],
                            ]],
                            ['path' => 'request.t_sep.jaminan.penjamin.tglKejadian', 'label' => 'Tgl Kejadian', 'type' => 'text', 'value' => ''],
                            ['path' => 'request.t_sep.jaminan.penjamin.keterangan', 'label' => 'Keterangan Penjamin', 'type' => 'text', 'value' => ''],
                            ['path' => 'request.t_sep.jaminan.penjamin.suplesi.suplesi', 'label' => 'Suplesi', 'type' => 'select', 'value' => '0', 'options' => [
                                ['label' => '0 - Tidak', 'value' => '0'],
                                ['label' => '1 - Ya', 'value' => '1'],
                            ]],
                            ['path' => 'request.t_sep.jaminan.penjamin.suplesi.noSepSuplesi', 'label' => 'No. SEP Suplesi', 'type' => 'text', 'value' => ''],
                            ['path' => 'request.t_sep.jaminan.penjamin.suplesi.lokasiLaka.kdPropinsi', 'label' => 'Kode Propinsi', 'type' => 'text', 'value' => ''],
                            ['path' => 'request.t_sep.jaminan.penjamin.suplesi.lokasiLaka.kdKabupaten', 'label' => 'Kode Kabupaten', 'type' => 'text', 'value' => ''],
                            ['path' => 'request.t_sep.jaminan.penjamin.suplesi.lokasiLaka.kdKecamatan', 'label' => 'Kode Kecamatan', 'type' => 'text', 'value' => ''],
                            ['path' => 'request.t_sep.dpjpLayan', 'label' => 'DPJP Layan', 'type' => 'text', 'value' => '46'],
                            ['path' => 'request.t_sep.noTelp', 'label' => 'No. Telepon', 'type' => 'text', 'value' => '08522038363'],
                            ['path' => 'request.t_sep.user', 'label' => 'User', 'type' => 'text', 'value' => 'Cobaws'],
                        ],
                        mockResponse: [
                            'metaData' => ['code' => '200', 'message' => 'Sukses'],
                            'response' => '1101R0070420V000017',
                        ],
                    ),
                    $this->form(
                        id: 'sep-delete',
                        title: 'Hapus SEP',
                        method: 'DELETE',
                        path: '/api/v1/bpjs/sep',
                        description: 'Menghapus SEP.',
                        fields: [
                            ['path' => 'request.t_sep.noSep', 'label' => 'No. SEP', 'type' => 'text', 'value' => '0301R0110326V000001'],
                            ['path' => 'request.t_sep.user', 'label' => 'User', 'type' => 'text', 'value' => 'admin-ui'],
                        ],
                        mockResponse: [
                            'metaData' => ['code' => '200', 'message' => 'OK'],
                            'response' => '0301R0011017V000007',
                        ],
                    ),
                    $this->query(
                        id: 'monitoring-kunjungan',
                        title: 'Monitoring Kunjungan',
                        method: 'GET',
                        path: '/api/v1/bpjs/monitoring-kunjungan',
                        description: 'Monitoring kunjungan berdasarkan tanggal dan jenis pelayanan.',
                        fields: [
                            ['key' => 'tanggal', 'label' => 'Tanggal', 'type' => 'date', 'value' => '2026-03-19'],
                            ['key' => 'tipe', 'label' => 'Jenis Pelayanan', 'type' => 'select', 'value' => '2', 'options' => [
                                ['label' => '1 - Rawat Inap', 'value' => '1'],
                                ['label' => '2 - Rawat Jalan', 'value' => '2'],
                            ]],
                        ],
                        mockResponse: [
                            'metaData' => ['code' => '200', 'message' => 'Sukses'],
                            'response' => [
                                'sep' => [
                                    [
                                        'diagnosa' => 'K65.0',
                                        'jnsPelayanan' => 'R.Inap',
                                        'kelasRawat' => '2',
                                        'nama' => 'HANIF ABDURRAHMAN',
                                        'noKartu' => '0001819122189',
                                        'noSep' => '0301R00110170000004',
                                        'noRujukan' => '0301U01108180200084',
                                        'poli' => null,
                                        'tglPlgSep' => '2017-10-03',
                                        'tglSep' => '2017-10-01',
                                    ],
                                    [
                                        'diagnosa' => 'I50.0',
                                        'jnsPelayanan' => 'R.Inap',
                                        'kelasRawat' => '3',
                                        'nama' => 'ASRIZAL',
                                        'noKartu' => '0002283324674',
                                        'noSep' => '0301R00110170000005',
                                        'noRujukan' => '0301U01108180200184',
                                        'poli' => null,
                                        'tglPlgSep' => '2017-10-10',
                                        'tglSep' => '2017-10-01',
                                    ],
                                ],
                            ],
                        ],
                    ),
                    $this->query(
                        id: 'monitoring-klaim',
                        title: 'Monitoring Klaim',
                        method: 'GET',
                        path: '/api/v1/bpjs/monitoring-klaim',
                        description: 'Monitoring klaim BPJS.',
                        fields: [
                            ['key' => 'tanggal', 'label' => 'Tanggal', 'type' => 'date', 'value' => '2026-03-19'],
                            ['key' => 'tipe', 'label' => 'Jenis Pelayanan', 'type' => 'select', 'value' => '2', 'options' => [
                                ['label' => '1 - Rawat Inap', 'value' => '1'],
                                ['label' => '2 - Rawat Jalan', 'value' => '2'],
                            ]],
                            ['key' => 'status', 'label' => 'Status Klaim', 'type' => 'select', 'value' => '1', 'options' => [
                                ['label' => '1 - Pending', 'value' => '1'],
                                ['label' => '2 - Layak', 'value' => '2'],
                                ['label' => '3 - Tidak Layak', 'value' => '3'],
                            ]],
                        ],
                        mockResponse: [
                            'metaData' => ['code' => '200', 'message' => 'Sukses'],
                            'response' => [
                                'klaim' => [
                                    [
                                        'Inacbg' => [
                                            'kode' => 'N-3-15-0',
                                            'nama' => 'DIALYSIS',
                                        ],
                                        'biaya' => [
                                            'byPengajuan' => '991200',
                                            'bySetujui' => '0',
                                            'byTarifGruper' => '991200',
                                            'byTarifRS' => '1170689',
                                            'byTopup' => '0',
                                        ],
                                        'kelasRawat' => '3',
                                        'noFPK' => '',
                                        'noSEP' => '0301R00109170001280',
                                        'peserta' => [
                                            'nama' => 'NUR',
                                            'noKartu' => '0033681422715',
                                            'noMR' => '974956',
                                        ],
                                        'poli' => 'Hemodialisa',
                                        'status' => 'Proses Verifikasi',
                                        'tglPulang' => '2017-09-02',
                                        'tglSep' => '2017-09-02',
                                    ],
                                    [
                                        'Inacbg' => [
                                            'kode' => 'N-3-15-0',
                                            'nama' => 'DIALYSIS',
                                        ],
                                        'biaya' => [
                                            'byPengajuan' => '991200',
                                            'bySetujui' => '0',
                                            'byTarifGruper' => '991200',
                                            'byTarifRS' => '1015000',
                                            'byTopup' => '0',
                                        ],
                                        'kelasRawat' => '3',
                                        'noFPK' => '',
                                        'noSEP' => '0301R00109170000094',
                                        'peserta' => [
                                            'nama' => 'YUH',
                                            'noKartu' => '0223416974628',
                                            'noMR' => '878410',
                                        ],
                                        'poli' => 'Hemodialisa',
                                        'status' => 'Proses Verifikasi',
                                        'tglPulang' => '2017-09-02',
                                        'tglSep' => '2017-09-02',
                                    ],
                                ],
                            ],
                        ],
                    ),
                ],
            ],
            [
                'id' => 'referensi',
                'label' => 'Referensi',
                'items' => [
                    $this->query(
                        id: 'referensi-poli',
                        title: 'Referensi Poli',
                        method: 'GET',
                        path: '/api/v1/bpjs/referensi/poli',
                        description: 'Cari referensi poli BPJS.',
                        fields: [
                            ['key' => 'keyword', 'label' => 'Keyword', 'type' => 'text', 'value' => 'int'],
                        ],
                        mockResponse: [
                            'metaData' => ['code' => '200', 'message' => 'Sukses'],
                            'response' => [
                                'poli' => [
                                    [
                                        'kode' => 'ICU',
                                        'nama' => 'Intensive Care Unit',
                                    ],
                                    [
                                        'kode' => 'INT',
                                        'nama' => 'Poli Penyakit Dalam',
                                    ],
                                    [
                                        'kode' => 'IVP',
                                        'nama' => 'Intravena Pydografi',
                                    ],
                                ],
                            ],
                        ],
                    ),
                    $this->query(
                        id: 'referensi-diagnosa',
                        title: 'Referensi Diagnosa',
                        method: 'GET',
                        path: '/api/v1/bpjs/referensi/diagnosa',
                        description: 'Cari referensi diagnosa BPJS.',
                        fields: [
                            ['key' => 'keyword', 'label' => 'Keyword', 'type' => 'text', 'value' => 'k30'],
                        ],
                        mockResponse: [
                            'metaData' => ['code' => '200', 'message' => 'Sukses'],
                            'response' => [
                                'diagnosa' => [
                                    [
                                        'kode' => 'A04',
                                        'nama' => 'A04 - Other bacterial intestinal infections',
                                    ],
                                ],
                            ],
                        ],
                    ),
                    $this->query(
                        id: 'referensi-faskes',
                        title: 'Referensi Faskes',
                        method: 'GET',
                        path: '/api/v1/bpjs/referensi/faskes',
                        description: 'Cari referensi fasilitas kesehatan.',
                        fields: [
                            ['key' => 'keyword', 'label' => 'Keyword', 'type' => 'text', 'value' => 'rsud'],
                            ['key' => 'tipe', 'label' => 'Tipe Faskes', 'type' => 'select', 'value' => '2', 'options' => [
                                ['label' => '1 - Faskes 1', 'value' => '1'],
                                ['label' => '2 - Rumah Sakit', 'value' => '2'],
                            ]],
                        ],
                        mockResponse: [
                            'metaData' => ['code' => '200', 'message' => 'Sukses'],
                            'response' => [
                                'faskes' => [
                                    [
                                        'kode' => '00161001',
                                        'nama' => 'PUSKESMAS SANGIRAN - KAB. SIMEULUE',
                                    ],
                                    [
                                        'kode' => '00161002',
                                        'nama' => 'PUSKESMAS SIMEULUE - KAB. SIMEULUE',
                                    ],
                                ],
                            ],
                        ],
                    ),
                    $this->query(
                        id: 'referensi-dokter-dpjp',
                        title: 'Referensi Dokter DPJP',
                        method: 'GET',
                        path: '/api/v1/bpjs/referensi/dokter-dpjp',
                        description: 'Cari dokter DPJP berdasarkan spesialis dan tanggal pelayanan.',
                        fields: [
                            ['key' => 'kode', 'label' => 'Kode Spesialis', 'type' => 'text', 'value' => 'INT'],
                            ['key' => 'jenis', 'label' => 'Jenis Pelayanan', 'type' => 'select', 'value' => '2', 'options' => [
                                ['label' => '1 - Rawat Inap', 'value' => '1'],
                                ['label' => '2 - Rawat Jalan', 'value' => '2'],
                            ]],
                            ['key' => 'tgl', 'label' => 'Tanggal Pelayanan', 'type' => 'date', 'value' => '2026-03-19'],
                        ],
                        mockResponse: [
                            'metaData' => ['code' => '200', 'message' => 'Sukses'],
                            'response' => [
                                'list' => [
                                    [
                                        'kode' => '31486',
                                        'nama' => 'Satro Jadhit, dr',
                                    ],
                                    [
                                        'kode' => '31492',
                                        'nama' => 'Satroni Lawa, dr',
                                    ],
                                ],
                            ],
                        ],
                    ),
                    $this->query(
                        id: 'referensi-provinsi',
                        title: 'Referensi Provinsi',
                        method: 'GET',
                        path: '/api/v1/bpjs/referensi/provinsi',
                        description: 'Daftar provinsi.',
                        fields: [],
                        mockResponse: [
                            'metaData' => ['code' => '200', 'message' => 'Sukses'],
                            'response' => [
                                'list' => [
                                    [
                                        'kode' => '16',
                                        'nama' => 'Bali',
                                    ],
                                    [
                                        'kode' => '17',
                                        'nama' => 'Banten',
                                    ],
                                ],
                            ],
                        ],
                    ),
                    $this->query(
                        id: 'referensi-kabupaten',
                        title: 'Referensi Kabupaten',
                        method: 'GET',
                        path: '/api/v1/bpjs/referensi/kabupaten',
                        description: 'Daftar kabupaten berdasarkan provinsi.',
                        fields: [
                            ['key' => 'prov', 'label' => 'Kode Provinsi', 'type' => 'text', 'value' => '31'],
                        ],
                        mockResponse: [
                            'metaData' => ['code' => '200', 'message' => 'Sukses'],
                            'response' => [
                                'list' => [
                                    [
                                        'kode' => '0227',
                                        'nama' => 'KAB. BADUNG',
                                    ],
                                    [
                                        'kode' => '0230',
                                        'nama' => 'KAB. BANGLI',
                                    ],
                                ],
                            ],
                        ],
                    ),
                    $this->query(
                        id: 'referensi-kecamatan',
                        title: 'Referensi Kecamatan',
                        method: 'GET',
                        path: '/api/v1/bpjs/referensi/kecamatan',
                        description: 'Daftar kecamatan berdasarkan kabupaten.',
                        fields: [
                            ['key' => 'kab', 'label' => 'Kode Kabupaten', 'type' => 'text', 'value' => '3171'],
                        ],
                        mockResponse: [
                            'metaData' => ['code' => '200', 'message' => 'Sukses'],
                            'response' => [
                                'list' => [
                                    [
                                        'kode' => '3139',
                                        'nama' => 'KUTA',
                                    ],
                                    [
                                        'kode' => '3135',
                                        'nama' => 'KUTA UTARA',
                                    ],
                                ],
                            ],
                        ],
                    ),
                    $this->query(
                        id: 'referensi-prosedur',
                        title: 'Referensi Prosedur',
                        method: 'GET',
                        path: '/api/v1/bpjs/referensi/prosedur',
                        description: 'Cari referensi prosedur tindakan.',
                        fields: [
                            ['key' => 'keyword', 'label' => 'Keyword', 'type' => 'text', 'value' => 'operasi'],
                        ],
                        mockResponse: [
                            'metaData' => ['code' => '200', 'message' => 'Sukses'],
                            'response' => [
                                'procedure' => [
                                    [
                                        'kode' => '21.05',
                                        'nama' => '21.05 - Control of epistaxis by (transantral) ligation of the maxillary artery',
                                    ],
                                    [
                                        'kode' => '382.2',
                                        'nama' => '382.2 - Chronic atticoantral suppurative otitis media',
                                    ],
                                ],
                            ],
                        ],
                    ),
                ],
            ],
            [
                'id' => 'kontrol',
                'label' => 'Surat Kontrol & SPRI',
                'items' => [
                    $this->query(
                        id: 'surat-kontrol-list-tanggal',
                        title: 'List Rencana Kontrol by Tanggal',
                        method: 'GET',
                        path: '/api/v1/bpjs/surat-kontrol/list-tanggal',
                        description: 'Data rencana kontrol berdasarkan tanggal awal, tanggal akhir, dan filter pencarian.',
                        fields: [
                            ['key' => 'tgl_awal', 'label' => 'Tanggal Awal', 'type' => 'date', 'value' => '2021-03-01'],
                            ['key' => 'tgl_akhir', 'label' => 'Tanggal Akhir', 'type' => 'date', 'value' => '2021-03-31'],
                            ['key' => 'filter', 'label' => 'Filter', 'type' => 'select', 'value' => '1', 'options' => [
                                ['label' => '1 - Tanggal Entri', 'value' => '1'],
                                ['label' => '2 - Tanggal Rencana Kontrol', 'value' => '2'],
                            ]],
                        ],
                        mockResponse: [
                            'metaData' => [
                                'code' => '200',
                                'message' => 'Sukses',
                            ],
                            'response' => [
                                'list' => [
                                    [
                                        'noSuratKontrol' => '0301R0110321K000002',
                                        'jnsPelayanan' => 'Rawat Jalan',
                                        'jnsKontrol' => '2',
                                        'namaJnsKontrol' => 'Surat Kontrol',
                                        'tglRencanaKontrol' => '2021-03-18',
                                        'tglTerbitKontrol' => '2021-03-16',
                                        'noSepAsalKontrol' => '0301R0111018V000006',
                                        'poliAsal' => 'INT',
                                        'namaPoliAsal' => 'PENYAKIT DALAM',
                                        'poliTujuan' => 'INT',
                                        'namaPoliTujuan' => 'PENYAKIT DALAM',
                                        'tglSEP' => '2021-03-16',
                                        'kodeDokter' => '31479',
                                        'namaDokter' => 'Prof.dr.Yulius,SpPD, KGEH',
                                        'noKartu' => '0001882053808',
                                        'nama' => 'mela handayani',
                                    ],
                                ],
                            ],
                        ],
                    ),
                    $this->query(
                        id: 'surat-kontrol-list',
                        title: 'List Rencana Kontrol',
                        method: 'GET',
                        path: '/api/v1/bpjs/surat-kontrol/list',
                        description: 'Data rencana kontrol berdasarkan nomor kartu peserta, bulan, tahun, dan filter pencarian.',
                        fields: [
                            ['key' => 'bulan', 'label' => 'Bulan', 'type' => 'text', 'value' => '01'],
                            ['key' => 'tahun', 'label' => 'Tahun', 'type' => 'text', 'value' => '2022'],
                            ['key' => 'no_kartu', 'label' => 'Nomor Kartu', 'type' => 'text', 'value' => '0002035874204'],
                            ['key' => 'filter', 'label' => 'Filter', 'type' => 'select', 'value' => '1', 'options' => [
                                ['label' => '1 - Tanggal Entri', 'value' => '1'],
                                ['label' => '2 - Tanggal Rencana Kontrol', 'value' => '2'],
                            ]],
                        ],
                        mockResponse: [
                            'metaData' => [
                                'code' => '200',
                                'message' => 'Sukses',
                            ],
                            'response' => [
                                'list' => [
                                    [
                                        'noSuratKontrol' => '0117R0770122K000004',
                                        'jnsPelayanan' => 'Rawat Inap',
                                        'jnsKontrol' => '2',
                                        'namaJnsKontrol' => 'Surat Kontrol',
                                        'tglRencanaKontrol' => '2022-01-06',
                                        'tglTerbitKontrol' => '2022-01-05',
                                        'noSepAsalKontrol' => '0117R0770122V000003',
                                        'poliAsal' => 'INT',
                                        'namaPoliAsal' => '-',
                                        'poliTujuan' => 'INT',
                                        'namaPoliTujuan' => 'PENYAKIT DALAM',
                                        'tglSEP' => '2022-01-04',
                                        'kodeDokter' => '296676',
                                        'namaDokter' => 'ABD KADIR',
                                        'noKartu' => '0002035874204',
                                        'nama' => 'ANI AZKIA',
                                        'terbitSEP' => 'Belum',
                                    ],
                                ],
                            ],
                        ],
                    ),
                    $this->query(
                        id: 'surat-kontrol-detail',
                        title: 'Cari Nomor Surat Kontrol',
                        method: 'GET',
                        path: '/api/v1/bpjs/surat-kontrol/detail',
                        description: 'Melihat detail nomor surat kontrol untuk kebutuhan kontrol lanjutan peserta.',
                        fields: [
                            ['key' => 'no_surat_kontrol', 'label' => 'Nomor Surat Kontrol', 'type' => 'text', 'value' => '0301R0111125K000002'],
                        ],
                        mockResponse: [
                            'metaData' => [
                                'code' => '200',
                                'message' => 'Sukses',
                            ],
                            'response' => [
                                'noSuratKontrol' => '0301R0111125K000002',
                                'tglRencanaKontrol' => '2025-11-25',
                                'tglTerbit' => '2025-11-18',
                                'jnsKontrol' => '2',
                                'poliTujuan' => 'BED',
                                'namaPoliTujuan' => 'BEDAH',
                                'kodeDokter' => '31348',
                                'namaDokter' => 'CIiNatXXAXSkrIrPId,ManFs.SDDMe',
                                'flagKontrol' => 'False',
                                'kodeDokterPembuat' => '31348',
                                'namaDokterPembuat' => 'CIiNatXXAXSkrIrPId,ManFs.SDDMe',
                                'namaJnsKontrol' => 'Kontrol',
                                'sep' => [
                                    'noSep' => '0301R0110725V000006',
                                    'tglSep' => '2025-07-30',
                                    'jnsPelayanan' => 'Rawat Jalan',
                                    'poli' => 'BED - BEDAH',
                                    'diagnosa' => 'E10 - Insulin-dependent diabetes mellitus',
                                    'peserta' => [
                                        'noKartu' => '0002482505324',
                                        'nama' => 'ARMSTIOFIALR',
                                        'tglLahir' => '1983-09-07',
                                        'kelamin' => 'P',
                                        'hakKelas' => '-',
                                    ],
                                    'provUmum' => [
                                        'kdProvider' => '10210901',
                                        'nmProvider' => 'KERTASEMAYA',
                                    ],
                                    'provPerujuk' => [
                                        'kdProviderPerujuk' => '0050B107',
                                        'nmProviderPerujuk' => 'Klinik Sehat Gajah Mada',
                                        'asalRujukan' => '1',
                                        'noRujukan' => '0050B1070924P000001',
                                        'tglRujukan' => '2025-10-01',
                                    ],
                                ],
                                'formPRB' => [
                                    'kdStatusPRB' => null,
                                    'data' => [
                                        'HBA1C' => null,
                                        'GDP' => null,
                                        'GD2JPP' => null,
                                        'eGFR' => null,
                                        'TD_Sistolik' => null,
                                        'TD_Diastolik' => null,
                                        'LDL' => null,
                                        'Rata_TD_Sistolik' => null,
                                        'Rata_TD_Diastolik' => null,
                                        'JantungKoroner' => null,
                                        'Stroke' => null,
                                        'VaskularPerifer' => null,
                                        'Aritmia' => null,
                                        'AtrialFibrilasi' => null,
                                        'SesakNapas3Bulan' => null,
                                        'NyeriDada3Bulan' => null,
                                        'Terkontrol' => null,
                                        'Gejala2xMinggu' => null,
                                        'BangunMalam' => null,
                                        'KeterbatasanFisik' => null,
                                        'FungsiParu' => null,
                                        'SkorMMRC' => null,
                                        'Eksaserbasi1Tahun' => null,
                                        'MampuAktivitas' => null,
                                        'Epileptik6Bulan' => null,
                                        'EfekSampingOAB' => null,
                                        'HamilMenyusui' => null,
                                        'Remisi' => null,
                                        'TerapiRumatan' => null,
                                        'Usia' => null,
                                        'AsamUrat' => null,
                                        'RemisiSLE' => null,
                                        'Hamil' => null,
                                        'NadiIstirahat' => null,
                                        'SesakNapasAktivitas' => null,
                                        'NyeriDadaAktivitas' => null,
                                    ],
                                ],
                            ],
                        ],
                    ),
                    $this->query(
                        id: 'surat-kontrol-cari-sep',
                        title: 'Cari SEP Surat Kontrol',
                        method: 'GET',
                        path: '/api/v1/bpjs/surat-kontrol/sep',
                        description: 'Melihat data SEP untuk keperluan rencana kontrol berdasarkan nomor SEP peserta.',
                        fields: [
                            ['key' => 'no_sep', 'label' => 'Nomor SEP', 'type' => 'text', 'value' => '0301R0010819V006059'],
                        ],
                        mockResponse: [
                            'metaData' => [
                                'code' => '200',
                                'message' => 'Sukses',
                            ],
                            'response' => [
                                'noSep' => '0301R0010819V006059',
                                'tglSep' => '2019-10-17',
                                'jnsPelayanan' => 'Rawat Jalan',
                                'poli' => 'HDL - HEMODIALISA',
                                'diagnosa' => 'Z49.1 - Extracorporeal dialysis',
                                'peserta' => [
                                    'noKartu' => '0000018965349',
                                    'nama' => 'RASBEN',
                                    'tglLahir' => '1957-11-10',
                                    'kelamin' => 'L',
                                    'hakKelas' => '-',
                                ],
                                'provUmum' => [
                                    'kdProvider' => '03100202',
                                    'nmProvider' => 'KAMPUNG TELENG',
                                ],
                                'provPerujuk' => [
                                    'kdProviderPerujuk' => '03100202',
                                    'nmProviderPerujuk' => 'KAMPUNG TELENG',
                                    'asalRujukan' => '1',
                                    'noRujukan' => '031002020619P000413',
                                    'tglRujukan' => '2019-10-17',
                                ],
                            ],
                        ],
                    ),
                    $this->form(
                        id: 'surat-kontrol-insert',
                        title: 'Insert Surat Kontrol',
                        method: 'POST',
                        path: '/api/v1/bpjs/surat-kontrol/insert',
                        description: 'Membuat surat kontrol baru.',
                        fields: [
                            ['path' => 'ui.is_prb', 'label' => 'Mode PRB', 'type' => 'select', 'value' => '0', 'options' => [
                                ['label' => 'Tidak', 'value' => '0'],
                                ['label' => 'Ya', 'value' => '1'],
                            ]],
                            ['path' => 'request.noSEP', 'label' => 'No. SEP', 'type' => 'text', 'value' => '0301R0111018V000006'],
                            ['path' => 'request.kodeDokter', 'label' => 'Kode Dokter', 'type' => 'text', 'value' => '12345'],
                            ['path' => 'request.poliKontrol', 'label' => 'Poli Kontrol', 'type' => 'text', 'value' => 'INT'],
                            ['path' => 'request.tglRencanaKontrol', 'label' => 'Tanggal Rencana Kontrol', 'type' => 'date', 'value' => '2026-03-20'],
                            ['path' => 'request.user', 'label' => 'User', 'type' => 'text', 'value' => 'admin-ui'],
                            ['path' => 'request.formPRB.kdStatusPRB', 'label' => 'Kode Status PRB', 'type' => 'text', 'value' => '07', 'showWhen' => ['path' => 'ui.is_prb', 'equals' => '1']],
                            ['path' => 'request.formPRB.data.HBA1C', 'label' => 'HBA1C', 'type' => 'text', 'value' => '', 'showWhen' => ['path' => 'ui.is_prb', 'equals' => '1']],
                            ['path' => 'request.formPRB.data.GDP', 'label' => 'GDP', 'type' => 'number', 'value' => '78', 'showWhen' => ['path' => 'ui.is_prb', 'equals' => '1']],
                            ['path' => 'request.formPRB.data.GD2JPP', 'label' => 'GD2JPP', 'type' => 'text', 'value' => '', 'showWhen' => ['path' => 'ui.is_prb', 'equals' => '1']],
                            ['path' => 'request.formPRB.data.eGFR', 'label' => 'eGFR', 'type' => 'text', 'value' => '', 'showWhen' => ['path' => 'ui.is_prb', 'equals' => '1']],
                            ['path' => 'request.formPRB.data.TD_Sistolik', 'label' => 'TD Sistolik', 'type' => 'number', 'value' => '90', 'showWhen' => ['path' => 'ui.is_prb', 'equals' => '1']],
                            ['path' => 'request.formPRB.data.TD_Diastolik', 'label' => 'TD Diastolik', 'type' => 'number', 'value' => '90', 'showWhen' => ['path' => 'ui.is_prb', 'equals' => '1']],
                            ['path' => 'request.formPRB.data.LDL', 'label' => 'LDL', 'type' => 'number', 'value' => '20', 'showWhen' => ['path' => 'ui.is_prb', 'equals' => '1']],
                            ['path' => 'request.formPRB.data.Rata_TD_Sistolik', 'label' => 'Rata-rata TD Sistolik', 'type' => 'text', 'value' => '', 'showWhen' => ['path' => 'ui.is_prb', 'equals' => '1']],
                            ['path' => 'request.formPRB.data.Rata_TD_Diastolik', 'label' => 'Rata-rata TD Diastolik', 'type' => 'text', 'value' => '', 'showWhen' => ['path' => 'ui.is_prb', 'equals' => '1']],
                            ['path' => 'request.formPRB.data.JantungKoroner', 'label' => 'Jantung Koroner', 'type' => 'text', 'value' => '', 'showWhen' => ['path' => 'ui.is_prb', 'equals' => '1']],
                            ['path' => 'request.formPRB.data.Stroke', 'label' => 'Stroke', 'type' => 'text', 'value' => '', 'showWhen' => ['path' => 'ui.is_prb', 'equals' => '1']],
                            ['path' => 'request.formPRB.data.VaskularPerifer', 'label' => 'Vaskular Perifer', 'type' => 'text', 'value' => '', 'showWhen' => ['path' => 'ui.is_prb', 'equals' => '1']],
                            ['path' => 'request.formPRB.data.Aritmia', 'label' => 'Aritmia', 'type' => 'text', 'value' => '', 'showWhen' => ['path' => 'ui.is_prb', 'equals' => '1']],
                            ['path' => 'request.formPRB.data.AtrialFibrilasi', 'label' => 'Atrial Fibrilasi', 'type' => 'text', 'value' => '', 'showWhen' => ['path' => 'ui.is_prb', 'equals' => '1']],
                            ['path' => 'request.formPRB.data.NadiIstirahat', 'label' => 'Nadi Istirahat', 'type' => 'text', 'value' => '', 'showWhen' => ['path' => 'ui.is_prb', 'equals' => '1']],
                            ['path' => 'request.formPRB.data.SesakNapas3Bulan', 'label' => 'Sesak Napas 3 Bulan', 'type' => 'text', 'value' => '', 'showWhen' => ['path' => 'ui.is_prb', 'equals' => '1']],
                            ['path' => 'request.formPRB.data.NyeriDada3Bulan', 'label' => 'Nyeri Dada 3 Bulan', 'type' => 'text', 'value' => '', 'showWhen' => ['path' => 'ui.is_prb', 'equals' => '1']],
                            ['path' => 'request.formPRB.data.SesakNapasAktivitas', 'label' => 'Sesak Napas Aktivitas', 'type' => 'text', 'value' => '', 'showWhen' => ['path' => 'ui.is_prb', 'equals' => '1']],
                            ['path' => 'request.formPRB.data.NyeriDadaAktivitas', 'label' => 'Nyeri Dada Aktivitas', 'type' => 'text', 'value' => '', 'showWhen' => ['path' => 'ui.is_prb', 'equals' => '1']],
                            ['path' => 'request.formPRB.data.Terkontrol', 'label' => 'Terkontrol', 'type' => 'text', 'value' => '', 'showWhen' => ['path' => 'ui.is_prb', 'equals' => '1']],
                            ['path' => 'request.formPRB.data.Gejala2xMinggu', 'label' => 'Gejala 2x Minggu', 'type' => 'text', 'value' => '', 'showWhen' => ['path' => 'ui.is_prb', 'equals' => '1']],
                            ['path' => 'request.formPRB.data.BangunMalam', 'label' => 'Bangun Malam', 'type' => 'text', 'value' => '', 'showWhen' => ['path' => 'ui.is_prb', 'equals' => '1']],
                            ['path' => 'request.formPRB.data.KeterbatasanFisik', 'label' => 'Keterbatasan Fisik', 'type' => 'text', 'value' => '', 'showWhen' => ['path' => 'ui.is_prb', 'equals' => '1']],
                            ['path' => 'request.formPRB.data.FungsiParu', 'label' => 'Fungsi Paru', 'type' => 'text', 'value' => '', 'showWhen' => ['path' => 'ui.is_prb', 'equals' => '1']],
                            ['path' => 'request.formPRB.data.SkorMMRC', 'label' => 'Skor MMRC', 'type' => 'text', 'value' => '', 'showWhen' => ['path' => 'ui.is_prb', 'equals' => '1']],
                            ['path' => 'request.formPRB.data.Eksaserbasi1Tahun', 'label' => 'Eksaserbasi 1 Tahun', 'type' => 'text', 'value' => '', 'showWhen' => ['path' => 'ui.is_prb', 'equals' => '1']],
                            ['path' => 'request.formPRB.data.MampuAktivitas', 'label' => 'Mampu Aktivitas', 'type' => 'text', 'value' => '', 'showWhen' => ['path' => 'ui.is_prb', 'equals' => '1']],
                            ['path' => 'request.formPRB.data.Epileptik6Bulan', 'label' => 'Epileptik 6 Bulan', 'type' => 'text', 'value' => '', 'showWhen' => ['path' => 'ui.is_prb', 'equals' => '1']],
                            ['path' => 'request.formPRB.data.EfekSampingOAB', 'label' => 'Efek Samping OAB', 'type' => 'text', 'value' => '', 'showWhen' => ['path' => 'ui.is_prb', 'equals' => '1']],
                            ['path' => 'request.formPRB.data.HamilMenyusui', 'label' => 'Hamil Menyusui', 'type' => 'text', 'value' => '', 'showWhen' => ['path' => 'ui.is_prb', 'equals' => '1']],
                            ['path' => 'request.formPRB.data.Remisi', 'label' => 'Remisi', 'type' => 'text', 'value' => '', 'showWhen' => ['path' => 'ui.is_prb', 'equals' => '1']],
                            ['path' => 'request.formPRB.data.TerapiRumatan', 'label' => 'Terapi Rumatan', 'type' => 'text', 'value' => '', 'showWhen' => ['path' => 'ui.is_prb', 'equals' => '1']],
                            ['path' => 'request.formPRB.data.Usia', 'label' => 'Usia', 'type' => 'text', 'value' => '', 'showWhen' => ['path' => 'ui.is_prb', 'equals' => '1']],
                            ['path' => 'request.formPRB.data.AsamUrat', 'label' => 'Asam Urat', 'type' => 'number', 'value' => '0.1', 'showWhen' => ['path' => 'ui.is_prb', 'equals' => '1']],
                            ['path' => 'request.formPRB.data.RemisiSLE', 'label' => 'Remisi SLE', 'type' => 'text', 'value' => '', 'showWhen' => ['path' => 'ui.is_prb', 'equals' => '1']],
                            ['path' => 'request.formPRB.data.Hamil', 'label' => 'Hamil', 'type' => 'text', 'value' => '', 'showWhen' => ['path' => 'ui.is_prb', 'equals' => '1']],
                        ],
                        mockResponse: [
                            'metaData' => ['code' => '200', 'message' => 'Ok'],
                            'response' => [
                                'noSuratKontrol' => '0301R0110520K000013',
                                'tglRencanaKontrol' => '2020-05-15',
                                'namaDokter' => 'Dr. John Wick',
                                'noKartu' => '0001328186441',
                                'nama' => 'ARIS',
                                'kelamin' => 'Laki-laki',
                                'tglLahir' => '1947-12-31',
                                'namaDiagnosa' => 'I60 - Subarachnoid haemorrhage',
                                'formPRB' => [
                                    'kdStatusPRB' => '07',
                                    'data' => [
                                        'HBA1C' => null,
                                        'GDP' => 78,
                                        'GD2JPP' => null,
                                        'eGFR' => null,
                                        'TD_Sistolik' => 90,
                                        'TD_Diastolik' => 90,
                                        'LDL' => 20,
                                        'Rata_TD_Sistolik' => null,
                                        'Rata_TD_Diastolik' => null,
                                        'JantungKoroner' => null,
                                        'Stroke' => null,
                                        'VaskularPerifer' => null,
                                        'Aritmia' => null,
                                        'AtrialFibrilasi' => null,
                                        'SesakNapas3Bulan' => null,
                                        'NyeriDada3Bulan' => null,
                                        'Terkontrol' => null,
                                        'Gejala2xMinggu' => null,
                                        'BangunMalam' => null,
                                        'KeterbatasanFisik' => null,
                                        'FungsiParu' => null,
                                        'SkorMMRC' => null,
                                        'Eksaserbasi1Tahun' => null,
                                        'MampuAktivitas' => null,
                                        'Epileptik6Bulan' => null,
                                        'EfekSampingOAB' => null,
                                        'HamilMenyusui' => null,
                                        'Remisi' => null,
                                        'TerapiRumatan' => null,
                                        'Usia' => null,
                                        'AsamUrat' => 0.1,
                                        'RemisiSLE' => null,
                                        'Hamil' => null,
                                        'NadiIstirahat' => null,
                                        'SesakNapasAktivitas' => null,
                                        'NyeriDadaAktivitas' => null,
                                    ],
                                ],
                            ],
                        ],
                    ),
                    $this->form(
                        id: 'surat-kontrol-update',
                        title: 'Update Surat Kontrol',
                        method: 'POST',
                        path: '/api/v1/bpjs/surat-kontrol/update',
                        description: 'Memperbarui surat kontrol.',
                        fields: [
                            ['path' => 'ui.is_prb', 'label' => 'Mode PRB', 'type' => 'select', 'value' => '0', 'options' => [
                                ['label' => 'Tidak', 'value' => '0'],
                                ['label' => 'Ya', 'value' => '1'],
                            ]],
                            ['path' => 'request.noSuratKontrol', 'label' => 'No. Surat Kontrol', 'type' => 'text', 'value' => '0301R0110321K000002'],
                            ['path' => 'request.noSEP', 'label' => 'No. SEP', 'type' => 'text', 'value' => '0301R0111018V000006'],
                            ['path' => 'request.kodeDokter', 'label' => 'Kode Dokter', 'type' => 'text', 'value' => '11111'],
                            ['path' => 'request.poliKontrol', 'label' => 'Poli Kontrol', 'type' => 'text', 'value' => 'INT'],
                            ['path' => 'request.tglRencanaKontrol', 'label' => 'Tanggal Rencana Kontrol', 'type' => 'date', 'value' => '2021-03-18'],
                            ['path' => 'request.user', 'label' => 'User', 'type' => 'text', 'value' => 'coba'],
                            ['path' => 'request.formPRB.kdStatusPRB', 'label' => 'Kode Status PRB', 'type' => 'text', 'value' => '07', 'showWhen' => ['path' => 'ui.is_prb', 'equals' => '1']],
                            ['path' => 'request.formPRB.data.HBA1C', 'label' => 'HBA1C', 'type' => 'text', 'value' => '', 'showWhen' => ['path' => 'ui.is_prb', 'equals' => '1']],
                            ['path' => 'request.formPRB.data.GDP', 'label' => 'GDP', 'type' => 'number', 'value' => '78', 'showWhen' => ['path' => 'ui.is_prb', 'equals' => '1']],
                            ['path' => 'request.formPRB.data.GD2JPP', 'label' => 'GD2JPP', 'type' => 'text', 'value' => '', 'showWhen' => ['path' => 'ui.is_prb', 'equals' => '1']],
                            ['path' => 'request.formPRB.data.eGFR', 'label' => 'eGFR', 'type' => 'text', 'value' => '', 'showWhen' => ['path' => 'ui.is_prb', 'equals' => '1']],
                            ['path' => 'request.formPRB.data.TD_Sistolik', 'label' => 'TD Sistolik', 'type' => 'number', 'value' => '90', 'showWhen' => ['path' => 'ui.is_prb', 'equals' => '1']],
                            ['path' => 'request.formPRB.data.TD_Diastolik', 'label' => 'TD Diastolik', 'type' => 'number', 'value' => '90', 'showWhen' => ['path' => 'ui.is_prb', 'equals' => '1']],
                            ['path' => 'request.formPRB.data.LDL', 'label' => 'LDL', 'type' => 'number', 'value' => '20', 'showWhen' => ['path' => 'ui.is_prb', 'equals' => '1']],
                            ['path' => 'request.formPRB.data.Rata_TD_Sistolik', 'label' => 'Rata-rata TD Sistolik', 'type' => 'text', 'value' => '', 'showWhen' => ['path' => 'ui.is_prb', 'equals' => '1']],
                            ['path' => 'request.formPRB.data.Rata_TD_Diastolik', 'label' => 'Rata-rata TD Diastolik', 'type' => 'text', 'value' => '', 'showWhen' => ['path' => 'ui.is_prb', 'equals' => '1']],
                            ['path' => 'request.formPRB.data.JantungKoroner', 'label' => 'Jantung Koroner', 'type' => 'text', 'value' => '', 'showWhen' => ['path' => 'ui.is_prb', 'equals' => '1']],
                            ['path' => 'request.formPRB.data.Stroke', 'label' => 'Stroke', 'type' => 'text', 'value' => '', 'showWhen' => ['path' => 'ui.is_prb', 'equals' => '1']],
                            ['path' => 'request.formPRB.data.VaskularPerifer', 'label' => 'Vaskular Perifer', 'type' => 'text', 'value' => '', 'showWhen' => ['path' => 'ui.is_prb', 'equals' => '1']],
                            ['path' => 'request.formPRB.data.Aritmia', 'label' => 'Aritmia', 'type' => 'text', 'value' => '', 'showWhen' => ['path' => 'ui.is_prb', 'equals' => '1']],
                            ['path' => 'request.formPRB.data.AtrialFibrilasi', 'label' => 'Atrial Fibrilasi', 'type' => 'text', 'value' => '', 'showWhen' => ['path' => 'ui.is_prb', 'equals' => '1']],
                            ['path' => 'request.formPRB.data.NadiIstirahat', 'label' => 'Nadi Istirahat', 'type' => 'text', 'value' => '', 'showWhen' => ['path' => 'ui.is_prb', 'equals' => '1']],
                            ['path' => 'request.formPRB.data.SesakNapas3Bulan', 'label' => 'Sesak Napas 3 Bulan', 'type' => 'text', 'value' => '', 'showWhen' => ['path' => 'ui.is_prb', 'equals' => '1']],
                            ['path' => 'request.formPRB.data.NyeriDada3Bulan', 'label' => 'Nyeri Dada 3 Bulan', 'type' => 'text', 'value' => '', 'showWhen' => ['path' => 'ui.is_prb', 'equals' => '1']],
                            ['path' => 'request.formPRB.data.Terkontrol', 'label' => 'Terkontrol', 'type' => 'text', 'value' => '', 'showWhen' => ['path' => 'ui.is_prb', 'equals' => '1']],
                            ['path' => 'request.formPRB.data.Gejala2xMinggu', 'label' => 'Gejala 2x Minggu', 'type' => 'text', 'value' => '', 'showWhen' => ['path' => 'ui.is_prb', 'equals' => '1']],
                            ['path' => 'request.formPRB.data.BangunMalam', 'label' => 'Bangun Malam', 'type' => 'text', 'value' => '', 'showWhen' => ['path' => 'ui.is_prb', 'equals' => '1']],
                            ['path' => 'request.formPRB.data.KeterbatasanFisik', 'label' => 'Keterbatasan Fisik', 'type' => 'text', 'value' => '', 'showWhen' => ['path' => 'ui.is_prb', 'equals' => '1']],
                            ['path' => 'request.formPRB.data.FungsiParu', 'label' => 'Fungsi Paru', 'type' => 'text', 'value' => '', 'showWhen' => ['path' => 'ui.is_prb', 'equals' => '1']],
                            ['path' => 'request.formPRB.data.SkorMMRC', 'label' => 'Skor MMRC', 'type' => 'text', 'value' => '', 'showWhen' => ['path' => 'ui.is_prb', 'equals' => '1']],
                            ['path' => 'request.formPRB.data.Eksaserbasi1Tahun', 'label' => 'Eksaserbasi 1 Tahun', 'type' => 'text', 'value' => '', 'showWhen' => ['path' => 'ui.is_prb', 'equals' => '1']],
                            ['path' => 'request.formPRB.data.MampuAktivitas', 'label' => 'Mampu Aktivitas', 'type' => 'text', 'value' => '', 'showWhen' => ['path' => 'ui.is_prb', 'equals' => '1']],
                            ['path' => 'request.formPRB.data.Epileptik6Bulan', 'label' => 'Epileptik 6 Bulan', 'type' => 'text', 'value' => '', 'showWhen' => ['path' => 'ui.is_prb', 'equals' => '1']],
                            ['path' => 'request.formPRB.data.EfekSampingOAB', 'label' => 'Efek Samping OAB', 'type' => 'text', 'value' => '', 'showWhen' => ['path' => 'ui.is_prb', 'equals' => '1']],
                            ['path' => 'request.formPRB.data.HamilMenyusui', 'label' => 'Hamil Menyusui', 'type' => 'text', 'value' => '', 'showWhen' => ['path' => 'ui.is_prb', 'equals' => '1']],
                            ['path' => 'request.formPRB.data.Remisi', 'label' => 'Remisi', 'type' => 'text', 'value' => '', 'showWhen' => ['path' => 'ui.is_prb', 'equals' => '1']],
                            ['path' => 'request.formPRB.data.TerapiRumatan', 'label' => 'Terapi Rumatan', 'type' => 'text', 'value' => '', 'showWhen' => ['path' => 'ui.is_prb', 'equals' => '1']],
                            ['path' => 'request.formPRB.data.Usia', 'label' => 'Usia', 'type' => 'text', 'value' => '', 'showWhen' => ['path' => 'ui.is_prb', 'equals' => '1']],
                            ['path' => 'request.formPRB.data.AsamUrat', 'label' => 'Asam Urat', 'type' => 'number', 'value' => '0.1', 'showWhen' => ['path' => 'ui.is_prb', 'equals' => '1']],
                            ['path' => 'request.formPRB.data.RemisiSLE', 'label' => 'Remisi SLE', 'type' => 'text', 'value' => '', 'showWhen' => ['path' => 'ui.is_prb', 'equals' => '1']],
                            ['path' => 'request.formPRB.data.Hamil', 'label' => 'Hamil', 'type' => 'text', 'value' => '', 'showWhen' => ['path' => 'ui.is_prb', 'equals' => '1']],
                            ['path' => 'request.formPRB.data.SesakNapasAktivitas', 'label' => 'Sesak Napas Aktivitas', 'type' => 'text', 'value' => '', 'showWhen' => ['path' => 'ui.is_prb', 'equals' => '1']],
                            ['path' => 'request.formPRB.data.NyeriDadaAktivitas', 'label' => 'Nyeri Dada Aktivitas', 'type' => 'text', 'value' => '', 'showWhen' => ['path' => 'ui.is_prb', 'equals' => '1']],
                        ],
                        mockResponse: [
                            'metaData' => ['code' => '200', 'message' => 'Ok'],
                            'response' => [
                                'noSuratKontrol' => '0301R0110520K000013',
                                'tglRencanaKontrol' => '2020-05-15',
                                'namaDokter' => 'Dr. John Wick',
                                'noKartu' => '0001328186441',
                                'nama' => 'ARIS',
                                'kelamin' => 'Laki-laki',
                                'tglLahir' => '1947-12-31',
                                'namaDiagnosa' => 'I60 - Subarachnoid haemorrhage',
                                'formPRB' => [
                                    'kdStatusPRB' => '07',
                                    'data' => [
                                        'HBA1C' => null,
                                        'GDP' => 78,
                                        'GD2JPP' => null,
                                        'eGFR' => null,
                                        'TD_Sistolik' => 90,
                                        'TD_Diastolik' => 90,
                                        'LDL' => 20,
                                        'Rata_TD_Sistolik' => null,
                                        'Rata_TD_Diastolik' => null,
                                        'JantungKoroner' => null,
                                        'Stroke' => null,
                                        'VaskularPerifer' => null,
                                        'Aritmia' => null,
                                        'AtrialFibrilasi' => null,
                                        'SesakNapas3Bulan' => null,
                                        'NyeriDada3Bulan' => null,
                                        'Terkontrol' => null,
                                        'Gejala2xMinggu' => null,
                                        'BangunMalam' => null,
                                        'KeterbatasanFisik' => null,
                                        'FungsiParu' => null,
                                        'SkorMMRC' => null,
                                        'Eksaserbasi1Tahun' => null,
                                        'MampuAktivitas' => null,
                                        'Epileptik6Bulan' => null,
                                        'EfekSampingOAB' => null,
                                        'HamilMenyusui' => null,
                                        'Remisi' => null,
                                        'TerapiRumatan' => null,
                                        'Usia' => null,
                                        'AsamUrat' => 0.1,
                                        'RemisiSLE' => null,
                                        'Hamil' => null,
                                        'NadiIstirahat' => null,
                                        'SesakNapasAktivitas' => null,
                                        'NyeriDadaAktivitas' => null,
                                    ],
                                ],
                            ],
                        ],
                    ),
                    $this->form(
                        id: 'spri-insert',
                        title: 'Insert SPRI',
                        method: 'POST',
                        path: '/api/v1/bpjs/spri/insert',
                        description: 'Membuat SPRI.',
                        fields: [
                            ['path' => 'request.noKartu', 'label' => 'No. Kartu', 'type' => 'text', 'value' => '0001116500714'],
                            ['path' => 'request.kodeDokter', 'label' => 'Kode Dokter', 'type' => 'text', 'value' => '31537'],
                            ['path' => 'request.poliKontrol', 'label' => 'Poli Kontrol', 'type' => 'text', 'value' => 'BED'],
                            ['path' => 'request.tglRencanaKontrol', 'label' => 'Tanggal Rencana Kontrol', 'type' => 'date', 'value' => '2021-04-13'],
                            ['path' => 'request.user', 'label' => 'User', 'type' => 'text', 'value' => 'sss'],
                        ],
                        mockResponse: [
                            'metaData' => ['code' => '200', 'message' => 'Ok'],
                            'response' => [
                                'noSPRI' => '0301R0110421K000002',
                                'tglRencanaKontrol' => '2021-04-20',
                                'namaDokter' => 'Dr.Yahya Marpaung,SpB, FINACS',
                                'noKartu' => '0001116500714',
                                'nama' => 'M AMRU',
                                'kelamin' => 'Laki-Laki',
                                'tglLahir' => '1997-12-16',
                                'namaDiagnosa' => null,
                            ],
                        ],
                    ),
                    $this->form(
                        id: 'spri-update',
                        title: 'Update SPRI',
                        method: 'POST',
                        path: '/api/v1/bpjs/spri/update',
                        description: 'Memperbarui SPRI.',
                        fields: [
                            ['path' => 'request.noSPRI', 'label' => 'No. SPRI', 'type' => 'text', 'value' => '0301R0110421K000116'],
                            ['path' => 'request.kodeDokter', 'label' => 'Kode Dokter', 'type' => 'text', 'value' => '31537'],
                            ['path' => 'request.poliKontrol', 'label' => 'Poli Kontrol', 'type' => 'text', 'value' => 'ANA'],
                            ['path' => 'request.tglRencanaKontrol', 'label' => 'Tanggal Rencana Kontrol', 'type' => 'date', 'value' => '2021-04-13'],
                            ['path' => 'request.user', 'label' => 'User', 'type' => 'text', 'value' => 'cobdda'],
                        ],
                        mockResponse: [
                            'metaData' => ['code' => '200', 'message' => 'Ok'],
                            'response' => [
                                'noSPRI' => '0301R0110421K000002',
                                'tglRencanaKontrol' => '2021-04-22',
                                'namaDokter' => 'Dr.Yahya Marpaung,SpB, FINACS',
                                'noKartu' => '0001116500714',
                                'nama' => 'M AMRU',
                                'kelamin' => 'Laki-Laki',
                                'tglLahir' => '1997-12-16',
                                'namaDiagnosa' => null,
                            ],
                        ],
                    ),
                ],
            ],
        ];
    }

    protected function query(
        string $id,
        string $title,
        string $method,
        string $path,
        string $description,
        array $fields,
        array $mockResponse
    ): array {
        return [
            'id' => $id,
            'title' => $title,
            'method' => $method,
            'path' => $path,
            'description' => $description,
            'mode' => 'query',
            'fields' => $fields,
            'mockResponses' => [
                'success' => $mockResponse,
                'failed' => $this->failedMockResponse(),
            ],
        ];
    }

    protected function form(
        string $id,
        string $title,
        string $method,
        string $path,
        string $description,
        array $fields,
        array $mockResponse
    ): array {
        return [
            'id' => $id,
            'title' => $title,
            'method' => $method,
            'path' => $path,
            'description' => $description,
            'mode' => 'form',
            'formFields' => $fields,
            'mockResponses' => [
                'success' => $mockResponse,
                'failed' => $this->failedMockResponse(),
            ],
        ];
    }

    protected function json(
        string $id,
        string $title,
        string $method,
        string $path,
        string $description,
        array $payload,
        array $mockResponse
    ): array {
        return [
            'id' => $id,
            'title' => $title,
            'method' => $method,
            'path' => $path,
            'description' => $description,
            'mode' => 'json',
            'jsonTemplate' => json_encode($payload, JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES),
            'mockResponses' => [
                'success' => $mockResponse,
                'failed' => $this->failedMockResponse(),
            ],
        ];
    }

    protected function failedMockResponse(): array
    {
        return [
            'metaData' => [
                'code' => '201',
                'message' => 'gagal',
            ],
            'response' => [],
        ];
    }

    protected function sepInsertPayload(): array
    {
        return [
            'request' => [
                't_sep' => [
                    'noKartu' => '0001234567890',
                    'tglSep' => '2026-03-19',
                    'ppkPelayanan' => '0301R011',
                    'jnsPelayanan' => '2',
                    'klsRawat' => [
                        'klsRawatHak' => '3',
                        'klsRawatNaik' => '',
                        'pembiayaan' => '',
                        'penanggungJawab' => '',
                    ],
                    'noMR' => 'RM-001',
                    'rujukan' => [
                        'asalRujukan' => '1',
                        'tglRujukan' => '2026-03-18',
                        'noRujukan' => 'RJK-001',
                        'ppkRujukan' => '0301P001',
                    ],
                    'catatan' => 'Kontrol dari dashboard admin',
                    'diagAwal' => 'K30',
                    'poli' => [
                        'tujuan' => 'INT',
                        'eksekutif' => '0',
                    ],
                    'cob' => [
                        'cob' => '0',
                    ],
                    'katarak' => [
                        'katarak' => '0',
                    ],
                    'jaminan' => [
                        'lakaLantas' => '0',
                        'noLP' => '',
                        'penjamin' => [
                            'tglKejadian' => '',
                            'keterangan' => '',
                            'suplesi' => [
                                'suplesi' => '0',
                                'noSepSuplesi' => '',
                                'lokasiLaka' => [
                                    'kdPropinsi' => '',
                                    'kdKabupaten' => '',
                                    'kdKecamatan' => '',
                                ],
                            ],
                        ],
                    ],
                    'tujuanKunj' => '0',
                    'flagProcedure' => '',
                    'kdPenunjang' => '',
                    'assesmentPel' => '',
                    'skdp' => [
                        'noSurat' => '',
                        'kodeDPJP' => '',
                    ],
                    'dpjpLayan' => '12345',
                    'noTelp' => '081234567890',
                    'user' => 'admin-ui',
                ],
            ],
        ];
    }
}
